[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Resilient Entrepreneur: Turning Setbacks into Opportunities and Learning from Mistakes to Build a Successful Business"
